name: Update Regional IPs
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:      # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and Filter
        run: |
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json > raw.json
          # Create files for different regions
          # 1. Get a list of all unique regions from the EC2 data
          # 2. Loop through them and create a file for each
          for region in $(jq -r '.prefixes[] | select(.service=="EC2") | .region' raw.json | sort -u); do
            jq -r --arg REG "$region" '.prefixes[] | select(.service=="EC2" and .region==$REG) | .ip_prefix' raw.json > "EC2-${region}.txt"
          done
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git commit -m "Update regional lists" || exit 0
          git push
